--- apps/desktop/desktop_native/core/Cargo.toml.orig	2025-04-28 18:52:32 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -81,7 +81,7 @@ desktop_objc = { path = "../objc" }
 security-framework-sys = { workspace = true, optional = true }
 desktop_objc = { path = "../objc" }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 oo7 = { workspace = true }
 libc = { workspace = true }
 
