--- apps/desktop/desktop_native/core/Cargo.toml.orig	2024-12-17 15:22:29 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -83,7 +83,7 @@ security-framework-sys = { version = "=2.12.0", option
 security-framework = { version = "=3.0.0", optional = true }
 security-framework-sys = { version = "=2.12.0", optional = true }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = { version = "=0.19.5", optional = true }
 libsecret = { version = "=0.5.0", optional = true }
 zbus = { version = "=4.4.0", optional = true }
