--- apps/desktop/desktop_native/core/Cargo.toml.orig	2025-01-23 11:12:57 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -79,7 +79,7 @@ desktop_objc = { path = "../objc" }
 security-framework-sys = { version = "=2.13.0", optional = true }
 desktop_objc = { path = "../objc" }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 oo7 = "=0.3.3"
 libc = "=0.2.169"
 
