--- apps/desktop/desktop_native/core/Cargo.toml.orig	2024-07-29 07:49:04 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -46,6 +46,6 @@ security-framework-sys = "=2.11.0"
 security-framework = "=2.11.0"
 security-framework-sys = "=2.11.0"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = "=0.19.5"
 libsecret = "=0.5.0"
