--- apps/desktop/desktop_native/Cargo.toml.orig	2024-01-09 15:12:51 UTC
+++ apps/desktop/desktop_native/Cargo.toml
@@ -53,6 +53,6 @@ security-framework-sys = "=2.9.1"
 security-framework = "=2.9.2"
 security-framework-sys = "=2.9.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = "=0.18.4"
 libsecret = "=0.4.0"
