--- apps/desktop/desktop_native/core/Cargo.toml.orig	2024-10-17 20:14:05 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -65,7 +65,7 @@ security-framework-sys = { version = "=2.11.0", option
 security-framework = { version = "=2.11.0", optional = true }
 security-framework-sys = { version = "=2.11.0", optional = true }
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = { version = "=0.19.5", optional = true }
 libsecret = { version = "=0.5.0", optional = true }
 zbus = { version = "=4.3.1", optional = true }
