--- apps/desktop/desktop_native/core/Cargo.toml.orig	2024-09-18 00:41:50 UTC
+++ apps/desktop/desktop_native/core/Cargo.toml
@@ -48,7 +48,7 @@ security-framework-sys = "=2.11.0"
 security-framework = "=2.11.0"
 security-framework-sys = "=2.11.0"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = "=0.19.5"
 libsecret = "=0.5.0"
 zbus = "=4.3.1"
