--- apps/desktop/desktop_native/Cargo.toml.orig	2023-11-06 18:50:48 UTC
+++ apps/desktop/desktop_native/Cargo.toml
@@ -53,6 +53,6 @@ core-foundation = "=0.9.3"
 security-framework = "=2.9.1"
 security-framework-sys = "=2.9.0"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = "=0.17.9"
 libsecret = "=0.3.0"
