--- apps/desktop/desktop_native/Cargo.toml.orig	2024-04-11 19:17:12 UTC
+++ apps/desktop/desktop_native/Cargo.toml
@@ -52,6 +52,6 @@ security-framework-sys = "=2.9.1"
 security-framework = "=2.9.2"
 security-framework-sys = "=2.9.1"
 
-[target.'cfg(target_os = "linux")'.dependencies]
+[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
 gio = "=0.19.2"
 libsecret = "=0.5.0"
