--- swc/crates/swc_malloc/Cargo.toml.orig	2024-11-04 02:42:20 UTC
+++ swc/crates/swc_malloc/Cargo.toml
@@ -13,8 +13,11 @@ bench = false
 
 [dependencies]
 
-[target.'cfg(not(target_os = "linux"))'.dependencies]
+[target.'cfg(not(any(target_os = "linux", target_os = "freebsd")))'.dependencies]
 mimalloc = { version = "0.1" }
+
+[target.'cfg(target_os = "freebsd")'.dependencies]
+mimalloc = { version = "0.1", features = ["local_dynamic_tls"] }
 
 [target.'cfg(all(target_os = "linux", target_env = "gnu", any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]
 tikv-jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
