--- rollup/rust/bindings_napi/Cargo.toml.orig	2024-07-08 15:11:26 UTC
+++ rollup/rust/bindings_napi/Cargo.toml
@@ -15,10 +15,10 @@ xxhash = { path = "../xxhash" }
 parse_ast = { path = "../parse_ast" }
 xxhash = { path = "../xxhash" }
 
-[target.'cfg(not(target_os = "linux"))'.dependencies]
+[target.'cfg(not(any(target_os = "linux", target_os = "freebsd")))'.dependencies]
 mimalloc-rust = { version = "0.2.1" }
 
-[target.'cfg(all(target_os = "linux", not(all(target_env = "musl", target_arch = "aarch64"))))'.dependencies]
+[target.'cfg(all(any(target_os = "linux", target_os = "freebsd"), not(all(target_env = "musl", target_arch = "aarch64"))))'.dependencies]
 mimalloc-rust = { version = "0.2.1", features = ["local-dynamic-tls"] }
 
 [build-dependencies]
