--- swc/crates/swc_malloc/Cargo.toml.orig	2025-03-24 03:58:03 UTC
+++ swc/crates/swc_malloc/Cargo.toml
@@ -13,10 +13,10 @@ bench = false
 
 [dependencies]
 
-[target.'cfg(not(any(target_os = "linux", target_family = "wasm", target_env = "musl", all(target_os = "linux", any(target_arch="aarch64", target_env = "gnu", target_arch="arm")))))'.dependencies]
+[target.'cfg(not(any(target_os = "linux", target_os = "freebsd", target_family = "wasm", target_env = "musl", all(target_os = "linux", any(target_arch="aarch64", target_env = "gnu", target_arch="arm")))))'.dependencies]
 mimalloc = { version = "0.1.43", features = [] }
 
-[target.'cfg(all(target_os = "linux", not(any(target_family = "wasm", target_env = "musl", all(target_os = "linux", target_env = "gnu", any(target_arch = "aarch64", target_arch = "arm"))))))'.dependencies]
+[target.'cfg(any(all(target_os = "linux", not(any(target_family = "wasm", target_env = "musl", all(target_os = "linux", target_env = "gnu", any(target_arch = "aarch64", target_arch = "arm"))))), target_os = "freebsd"))'.dependencies]
 mimalloc = { version = "0.1.43", features = ["local_dynamic_tls"] }
 
 [target.'cfg(all(target_os = "linux", target_env = "gnu", any(target_arch = "aarch64", target_arch = "arm")))'.dependencies]
